### ISSUE TITLE
problem!!, has one more solution

### ISSUE THREAD

**Issue by jungmoona** [rzippo/PicrossSolver#1]
hi i resarched  your picross sover logic
appreciate your code @rzippo 

i have question

see attachment json file.

my expected appearance figure like below.

1 o 1 o 1 o 1 o 1 o
o 1 o 1 o 1 o 1 o 1

but thats figure of resolved 

![image](https://user-images.githubusercontent.com/1295849/148534379-36992083-1351-429d-a05e-0b98f5fac6d0.png)

Where in the code should I edit?

[TEST2.zip](https://github.com/rzippo/PicrossSolver/files/7828372/TEST2.zip)

**Comment by rzippo** [comment]
The issue here is that the puzzle input does not lead to a unique solution, and I can't see how you could change it so that it does.
With your input, the solver will randomly yield one of the two possible solutions.

To extend the solver to obtain all possible solution, you would need to do some analytical work first: 

- how can you tell when a problem has more than one solution? 
- how can you tell when you have found all solutions?
- how can you tell, based on the solutions you have found so far, what cell(s) you should flip to find a new solution?

I do not know the answers to these, so I do not know what you should change.

**Comment by jungmoona** [comment]
i found solution project

https://github.com/Mattias1/picross

this project solved issue " one more solution "
